query CurrentOrganization {
  currentOrganization {
    _id
    createdAt
    updatedAt
    internalName
    name
    isActive
    operationalDays
    owner {
      _id
      email
      displayName
      pictureUrl
    }
  }
}

mutation UpdateCurrentOrganization($input: UpdateCurrentOrganizationInput!) {
  updateCurrentOrganization(input: $input) {
    _id
    internalName
    name
  }
}