query Organizations($query: FindOrganizationsPaginationArgs!, $sort: OrganizationsSortArgs) {
  organizations(query: $query, sort: $sort) {
    items {
      _id
      createdAt
      updatedAt
      internalName
      name
      isActive
      owner {
        _id
        email
        displayName
        pictureUrl
      }
    }
    hasNextPage
    hasPreviousPage
    page
    total
  }
}

query Organization($args: FindOrganizationArgs!) {
  organization(args: $args) {
    _id
    createdAt
    updatedAt
    internalName
    name
    isActive
    operationalDays
    owner {
      _id
      email
      displayName
      pictureUrl
    }
  }
}


mutation CreateOrganization($input: CreateOrganizationInput!) {
  createOrganization(input: $input) {
    _id
    internalName
    name
  }
}

mutation UpdateOrganization($input: UpdateOrganizationInput!) {
  updateOrganization(input: $input) {
    _id
    internalName
    name
  }
}