mutation LoginWithPassword($input: LoginPasswordInput!) {
  loginWithPassword(input: $input) {
    token
    user {
      _id
      createdAt
      isActive
      updatedAt
      firstName
      lastName
      email
      timezone
      pictureUrl
    }
  }
}